version: 0.1

phases:
    install:
        commands:
            - echo Installing Node.JS...
            - curl -sL https://deb.nodesource.com/setup_16.x | bash -
            - apt-get install -y nodejs
    pre_build:
        commands:
            - echo Installing dependencies...
            - npm i -g @angular/cli
            - npm install
    build:
        commands:
            - echo Linting...
            - npm run lint
            - echo Testing...
            - npm run ci-test
            - echo Building...
            - ng build --configuration production
            - echo Build finished.
artifacts:
    files:
        - '**/*'
    discard-paths: no
    base-directory: dist/platform-frontend
